version: 2
jobs:
  build:
    docker:
      - image: ruby:2.7
    working_directory: /app
    steps:
      - checkout
      - run: Run migrations
          command: bundle exec rake db:migrate
      - run: Run seed data
          command: bundle exec rake db:seed
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rspec
      # - run:
      #     name: Run Linter
      #     command: bundle exec rubocop
      # - run:
      #     name: Run Security Scan
      #     command: bundle exec brakeman
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
