version: 2.1
jobs:
  build:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/ruby:3.1.2-node
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: testuser
          POSTGRES_DB: wyshlist_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Parallel RSpec
          command: bundle exec rspec

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
