default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("WYSHLIST_DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("WYSHLIST_DATABASE_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("WYSHLIST_DATABASE_HOST") { "db" } %>
  port: <%= ENV.fetch("WYSHLIST_DATABASE_PORT") { "5432" } %>
#
default: &default
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wyshlist_database_development

test:
  <<: *default
  database: wyshlist_database_test

production:
  <<: *default
  database: wyshlist_database_production
  password: <%= ENV["WYSHLIST_DATABASE_PASSWORD"] %>
