meta_product_name: "Wyshlist"
meta_title: "contribute & vote on the next product lunch - Wyshlist"
meta_description: "Allow your team or customers to submit ideas and vote on their favorite"
meta_image: "logo.png"