name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby 3.1.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: Setup test database
      run: |
        sudo apt-get -yqq install libpq-dev
        cp config/database.ci.yml config/database.yml
        bundle exec rake db:create db:schema:load --trace

    - name: Run RSpec
      run: bundle exec rspec

    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
